# Dockerfile to install Orbit + Isaac Sim, with conda as the default env. 
# 
# Written by Özhan Özen, SBTC, Switzerland Innovation Park Biel/Bienne.
#
# RUN the following: 
#
# docker compose build --no-cache --progress=plain
# or 
# docker compose build --no-cache --progress=plain > build_output.txt 

ARG ISAACSIM_VERSION=2023.1.1

FROM nvcr.io/nvidia/isaac-sim:${ISAACSIM_VERSION}

ENV ORBIT_PATH=/workspace/orbit

### Use bash by default
SHELL ["/bin/bash", "-c"]

### Install Orbit
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
    build-essential \
    cmake \
    git \
    libglib2.0-0 \
    wget \
    ncurses-term && \
    apt -y autoremove && apt clean autoclean && \
    rm -rf /var/lib/apt/lists/* 

COPY ../../ ${ORBIT_PATH}

RUN DEBIAN_FRONTEND=noninteractive ln -sf "/isaac-sim" ${ORBIT_PATH}/_isaac_sim && \
    echo "alias orbit=${ORBIT_PATH}/orbit.sh" >> ${HOME}/.bashrc

RUN DEBIAN_FRONTEND=noninteractive \
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda && \
    rm Miniconda3-latest-Linux-x86_64.sh && \
    /opt/miniconda/bin/conda init bash

ENV PATH="/opt/miniconda/bin:$PATH"
RUN conda update -n base -c defaults conda 

RUN DEBIAN_FRONTEND=noninteractive ${ORBIT_PATH}/orbit.sh --conda && echo "conda deactivate && conda activate orbit" >> ${HOME}/.bashrc
SHELL ["/opt/miniconda/bin/conda", "run", "-n", "orbit", "/bin/bash", "-c"]

RUN DEBIAN_FRONTEND=noninteractive \
    ${ORBIT_PATH}/orbit.sh --install && \
    ${ORBIT_PATH}/orbit.sh --extra

WORKDIR ${ORBIT_PATH}/

COPY docker/sbtc/bash_scripts/runisaac.sh ./

RUN ln -s "/docs" ${ORBIT_PATH}/_docs && \
    echo "export LIVESTREAM=3" >> ${HOME}/.bashrc

### For some reason, psutil is not installed properly for isaac-sim
RUN DEBIAN_FRONTEND=noninteractive ${ORBIT_PATH}/_isaac_sim/python.sh -m pip install psutil

### Set entrypoint (adjust to your preferences)
ENTRYPOINT ["bash"]

